# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Python Warm-Up
author: Yen-Chia Hsu

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 600

# Information about where the book exists on the web
repository:
  url: https://github.com/MultiX-Amsterdam/python-warm-up  # Online location of your book
  path_to_book: /  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Add launch buttons
launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: ""

# Exclude files
exclude_patterns: [README.md]

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    # See here: https://jupyterbook.org/en/stable/customize/config.html
    - colon_fence
    - dollarmath
    - html_image
    - linkify
    - substitution
    - tasklist

sphinx:
  # This is to work around the bug of no syntax highlighting
  extra_extensions:
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    # This is for plotly to work
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
